### PR TITLE
feature/update awssdk to 3.7.3

### PR DESCRIPTION
**Pull request by CatalinPJ**

### CODE REVIEW

**Comment by DZ1M** [comment]
Up

**Review by DZ1M — APPROVED** [review]

**Review by MohamedR-Gantner — APPROVED** [review]

**Comment by MohamedR-Gantner** [comment]
Hey, 
Could this PR please be reviewed & merged?
It would fix issue #40 for my usecase, seeing as I am stuck with conflicting AWS.SQS packages.
It's a blocker for our net8 update seeing as we use Rebus to manage messages and the newest version depends on aws.sdk 3.7.300+.

**Comment by dietermijle** [comment]
+1

**Review by dietermijle — APPROVED** [review]

**Comment by dietermijle** [comment]
@raol Can we get this one merged, pls?

**Pull request merged**
