### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by RMaschkiwitz**
Updated the dependencies.

### CODE REVIEW

**Comment by RMaschkiwitz** [comment]
The build (release) action needs to be updated too. You can have a look at the workflow file for the action in the gantner-nv fork.

**Comment by djhvscf** [comment]
Any plan to merge this?

**Comment by raol** [comment]
Thanks a lot for your PR! Merging

**Comment by djhvscf** [comment]
This is the best of this day. Thanks

**Comment by djhvscf** [comment]
@raol did you create a new nuget package?

**Pull request merged**
