### PR TITLE
Support .Net Standard 1.6

### PR DESCRIPTION
**Pull request by tommed**
The dependencies all support NetStandard1.3 so let's get this supporting .Net Standard too :)

### CODE REVIEW

**Comment by ccelson** [comment]
Any chance we could get this reviewed?

**Comment by raol** [comment]
@ccelson  as far as I can see from README.md, you maintain separate project in you fork. There are references to this repo, like "this project is port from <this repo>" etc.
Do you still want to merge?
If so, I will review in the near future.

**Comment by ccelson** [comment]
@raol I was recently trying to pull this library into a .Net standard 1.6 project using Nuget, I didn't read the updated README, just noticed that it was a PR for .Net standard 1.6 updates. I would find it useful to have that support for sure, but its up to you

**Comment by dietermijle** [comment]
Any update on this one?
Would also like to port this to netstandard1.6.

**Comment by raol** [comment]
@dietermijle I've started making all necessary changes in #7. Hope to fix everything in one-two days.

**Comment by raol** [comment]
I'm closing this PR because finally I managed to port the library to netstandard 1.6 myself.

**Pull request closed without merging**
